name: "Update Pull Request"
on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: the-wright-jamie/update-pr-info-action@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '[a-z\d-_.\\/]+'
          head-branch-regex: "test"
          title-template: "[%headbranch%]"
          body-template: |
            Merging into '%basebranch%'
            [Link to ticket: %headbranch%](https://example.com/%headbranch%)
          body-update-action: "suffix"
